import {dictionary,type Locale} from '../lib/i18n';
import {growth,words} from './growth';
import {proof} from './proof';
import {testimonials,type Testimonial} from './testimonials';
export const caseOrder=['strongman','skyrocket-your-biz','akam','generation-atomic','bunchful','gourmet-gather','etsy','content-studio'] as const;
export type CaseSlug=typeof caseOrder[number];
export type Filter='all'|'paid-social'|'crm'|'seo-content'|'ecommerce';
export const filterIds:Filter[]=['all','paid-social','crm','seo-content','ecommerce'];
export type Case={slug:string;client:string;title:string;sector:string;ownership:'own'|'client'|'employer';role:string;timeline:string;channels:string[];stack:string[];summary:string;challenge:string;strategy:string;execution:string[];results:string[];nextStep:string;metrics:{value:string;label:string;timeframe:string;baseline?:string}[];quote?:Testimonial;images:{src:string;caption:string}[];links:{label:string;url:string}[];filters:Filter[]};
const setup:Record<CaseSlug,{ownership:Case['ownership'];channels:string[];filters:Filter[];title:[string,string,string];strategy:[string,string,string];next:[string,string,string]}>={
 'skyrocket-your-biz':{ownership:'own',channels:['Meta Ads','Email','SMS'],filters:['paid-social','crm'],title:['A lead-to-call funnel built in GoHighLevel','Un tunnel du prospect au rendez-vous dans GoHighLevel','مسار من العميل المحتمل إلى المكالمة في GoHighLevel'],strategy:['I connected acquisition and follow-up in one CRM so every form submission had a defined next step.','J’ai relié acquisition et suivi dans un même CRM pour donner une suite précise à chaque formulaire.','ربطت اكتساب العملاء والمتابعة في CRM واحد، لتكون لكل استمارة خطوة تالية واضحة.'],next:['I would compare each lead source with booked calls before reallocating budget.','Je comparerais chaque source de prospects aux appels réservés avant de réallouer le budget.','سأقارن كل مصدر للعملاء المحتملين بالمكالمات المحجوزة قبل إعادة توزيع الميزانية.']},
 strongman:{ownership:'employer',channels:['Facebook','Instagram','TikTok'],filters:['paid-social','seo-content'],title:['A content operation for a national strength-sports community','Une organisation éditoriale pour une communauté nationale de sports de force','منظومة محتوى لمجتمع وطني لرياضات القوة'],strategy:['I organized content around athletes and competitions, connecting the publishing calendar to event promotion.','J’ai organisé le contenu autour des athlètes et des compétitions, en reliant le calendrier éditorial aux événements.','نظمت المحتوى حول الرياضيين والمسابقات وربطت تقويم النشر بالترويج للفعاليات.'],next:['I would compare event enquiries by creative format to improve the next promotion cycle.','Je comparerais les demandes liées aux événements par format créatif pour améliorer le cycle suivant.','سأقارن استفسارات الفعاليات حسب نوع المحتوى لتحسين دورة الترويج التالية.']},
 bunchful:{ownership:'employer',channels:['Social','Search','Email'],filters:['seo-content','crm'],title:['A consistent digital presence for a generosity business','Une présence digitale cohérente pour une entreprise dédiée à la générosité','حضور رقمي متناسق لمؤسسة تعمل في العطاء'],strategy:['I aligned the website and social content around a shared editorial direction, with analytics supporting the next decisions.','J’ai aligné le site et les réseaux sociaux sur une même direction éditoriale, avec l’analyse pour guider les décisions.','وحدت اتجاه الموقع والمحتوى الاجتماعي تحريرياً، مع الاستعانة بالتحليلات لاتخاذ القرارات التالية.'],next:['I would use landing-page and email data to prioritize the next content updates.','J’utiliserais les données des pages et des emails pour prioriser les prochaines mises à jour.','سأستخدم بيانات صفحات الهبوط والبريد لترتيب أولويات تحديث المحتوى.']},
 akam:{ownership:'client',channels:['Instagram','Facebook','Meta Ads'],filters:['paid-social','seo-content'],title:['A reusable social playbook for New York property marketing','Un guide social réutilisable pour l’immobilier new-yorkais','دليل محتوى اجتماعي قابل لإعادة الاستخدام لعقارات نيويورك'],strategy:['I used local context and everyday amenities to make property content useful to prospective residents.','J’ai mis en avant le quartier et les équipements du quotidien pour rendre le contenu utile aux futurs résidents.','استخدمت سياق الحي والمرافق اليومية لجعل المحتوى العقاري مفيداً للسكان المحتملين.'],next:['I would connect enquiry quality to individual campaigns before expanding local targeting.','Je relierais la qualité des demandes aux campagnes avant d’élargir le ciblage local.','سأربط جودة الاستفسارات بكل حملة قبل توسيع الاستهداف المحلي.']},
 'gourmet-gather':{ownership:'own',channels:['Pinterest','Search','Email'],filters:['seo-content','crm'],title:['A recipe platform connecting search, Pinterest and email','Une plateforme de recettes reliant SEO, Pinterest et email','منصة وصفات تربط البحث وPinterest والبريد'],strategy:['I connected search-led publishing with Pinterest distribution and email capture so content had a route to repeat visits.','J’ai relié publication SEO, diffusion Pinterest et collecte email pour encourager les visites récurrentes.','ربطت النشر المبني على البحث بالتوزيع عبر Pinterest وجمع البريد لتشجيع الزيارات المتكررة.'],next:['I would compare returning visitors and email signups across the strongest recipe topics.','Je comparerais les visiteurs récurrents et les inscriptions email selon les thèmes de recettes.','سأقارن عودة الزوار والتسجيلات البريدية بين أبرز مواضيع الوصفات.']},
 etsy:{ownership:'own',channels:['Etsy','Pinterest'],filters:['ecommerce','seo-content'],title:['234 sales for my print-on-demand apparel store','234 ventes pour ma boutique de vêtements à la demande','234 مبيعة لمتجري للملابس المطبوعة حسب الطلب'],strategy:['I paired keyword-led listings with repeatable design and fulfilment workflows, keeping search and customer service in the same operation.','J’ai associé fiches optimisées et processus réutilisables de création et de livraison, en coordonnant recherche et service client.','جمعت بين قوائم مبنية على الكلمات المفتاحية وتدفقات تصميم وتنفيذ قابلة للتكرار، مع ربط البحث بخدمة العملاء.'],next:['I would compare conversion by listing and test new mockups on the most-viewed products.','Je comparerais la conversion par fiche et testerais de nouvelles maquettes sur les produits les plus vus.','سأقارن التحويل حسب القائمة وأختبر صور عرض جديدة للمنتجات الأكثر مشاهدة.']},
 'content-studio':{ownership:'own',channels:['WordPress','Pinterest','Social'],filters:['seo-content'],title:['Research to WordPress publishing in one desktop workflow','De la recherche à WordPress dans un seul flux de travail','من البحث إلى النشر في WordPress ضمن تطبيق مكتبي واحد'],strategy:['I connected repeated publishing tasks in one application while keeping a review step before publication.','J’ai regroupé les tâches récurrentes dans une application en conservant une vérification avant publication.','ربطت مهام النشر المتكررة في تطبيق واحد مع الحفاظ على خطوة مراجعة قبل النشر.'],next:['I would test the workflow with longer editorial batches and document where manual review is most useful.','Je testerais des lots éditoriaux plus longs et documenterais les étapes où la vérification manuelle est la plus utile.','سأختبر التدفق بدفعات تحريرية أكبر وأوثق الخطوات التي تستفيد أكثر من المراجعة اليدوية.']},
 'generation-atomic':{ownership:'employer',channels:['Facebook','LinkedIn','Twitter','Instagram'],filters:['seo-content','ecommerce'],title:['Content, search and event campaigns for clean-energy advocacy','Contenu, SEO et campagnes événementielles pour les énergies propres','محتوى وبحث وحملات فعاليات للتوعية بالطاقة النظيفة'],strategy:['I coordinated editorial content, search and event communications so each channel supported the same public-facing message.','J’ai coordonné contenu, recherche et communication événementielle autour d’un message public cohérent.','نسقت المحتوى التحريري والبحث واتصالات الفعاليات لتدعم القنوات رسالة عامة واحدة.'],next:['I would compare event signups by content topic to focus the next editorial calendar.','Je comparerais les inscriptions aux événements par thème pour orienter le prochain calendrier.','سأقارن تسجيلات الفعاليات حسب موضوع المحتوى لتوجيه التقويم التحريري التالي.']},
};
export function getCase(slug:CaseSlug,locale:Locale):Case {
 const p=dictionary(locale).work[slug],s=setup[slug],g=growth(locale),t=(v:[string,string,string])=>words(locale,...v);
 return {slug,client:slug==='etsy'?'ExclusiveShirtDesign':p.name,title:t(s.title),sector:p.category.split(' / ').at(-1)!,ownership:s.ownership,role:p.role,timeline:p.period,channels:s.channels,stack:p.tools,summary:p.intro,challenge:p.context,strategy:t(s.strategy),execution:p.approach,results:[p.delivered],nextStep:t(s.next),
  metrics:slug==='etsy'?[{value:proof.etsy.sales,label:g.sales,timeframe:g.since},{value:proof.etsy.listings,label:g.listings,timeframe:g.since},{value:proof.etsy.rating,label:g.etsyReviews,timeframe:g.since}]:[],
  quote:slug==='strongman'?testimonials[0]:undefined,
  images:p.proof.src?[{src:p.proof.src,caption:p.proof.caption}]:[],
  links:slug==='content-studio'?[{label:'GitHub',url:'https://github.com/mahdibouizmoune/content-studio'}]:slug==='etsy'?[{label:'ExclusiveShirtDesign · Etsy',url:proof.etsy.url}]:[],filters:s.filters};
}
