import type {Locale} from '../lib/i18n';
export const words = (locale:Locale, en:string, fr:string, ar:string) => ({en,fr,ar})[locale];
export function growth(locale:Locale) {
 const t=(en:string,fr:string,ar:string)=>words(locale,en,fr,ar);
 return {
  nav:[t('Work','Réalisations','أعمالي'),t('Services','Services','خدماتي'),t('Process','Méthode','طريقة عملي'),t('Reviews','Avis','التوصيات'),t('About','À propos','نبذة عني')],
  book:t('Contact me','Me contacter','تواصل معي'), menu:t('Open menu','Ouvrir le menu','افتح القائمة'), close:t('Close menu','Fermer le menu','أغلق القائمة'),
  hero:t('I run paid social and CRM systems that turn ad spend into booked calls and sales.','Je gère les campagnes publicitaires et les systèmes CRM qui transforment le budget média en rendez-vous et en ventes.','أدير الحملات الإعلانية وأنظمة إدارة علاقات العملاء لتحويل الإنفاق الإعلاني إلى مكالمات محجوزة ومبيعات.'),
  subline:t('Digital Marketing Manager. 8+ years across Meta, TikTok, Pinterest, GoHighLevel and GA4. English, French, Arabic.','Digital Marketing Manager. Plus de 8 ans sur Meta, TikTok, Pinterest, GoHighLevel et GA4. Anglais, français, arabe.','مدير تسويق رقمي. أكثر من 8 سنوات من الخبرة في Meta وTikTok وPinterest وGoHighLevel وGA4. أعمل بالعربية والفرنسية والإنجليزية.'),
  seeWork:t('See the work','Voir les réalisations','شاهد أعمالي'), now:t('Now: Marketing Automation & CRM Manager, Bunchful Enterprise','Actuellement : Responsable automatisation marketing et CRM, Bunchful Enterprise','حالياً: مدير أتمتة التسويق وCRM لدى Bunchful Enterprise'),
  location:t('Safi, Morocco · Remote worldwide','Safi, Maroc · À distance, dans le monde entier','آسفي، المغرب · أعمل عن بُعد حول العالم'),
  recommendation:t('LinkedIn recommendation','Recommandation LinkedIn','توصية على LinkedIn'),recommended:t('Recommended on LinkedIn','Recommandé sur LinkedIn','موصى بي على LinkedIn'),
  rating:t('5.0 · 76 reviews on Fiverr','5.0 · 76 avis sur Fiverr','5.0 · 76 تقييماً على Fiverr'), brands:t("Brands and teams I've worked with","Marques et équipes avec lesquelles j’ai travaillé",'علامات وفرق عملت معها'),
  work:t('Selected work','Réalisations sélectionnées','أعمال مختارة'),allWork:t('All work','Toutes les réalisations','جميع الأعمال'),readCase:t('Read the case','Lire l’étude de cas','اقرأ دراسة الحالة'),
  filters:[t('All','Tout','الكل'),t('Paid social','Publicité sociale','الإعلانات الاجتماعية'),t('CRM & automation','CRM et automatisation','CRM والأتمتة'),t('SEO & content','SEO et contenu','SEO والمحتوى'),t('E-commerce','E-commerce','التجارة الإلكترونية')],
  own:t('Own venture','Projet personnel','مشروعي الخاص'),client:t('Freelance client','Client indépendant','عميل مستقل'),employer:t('Employer','Employeur','جهة عمل'),
  approach:t('What changes when I take over','Ce qui change quand je prends le relais','ما الذي يتغير عندما أتولى العمل'),before:t('Before','Avant','قبل'),after:t('After','Après','بعد'),
  changes:[
   [t('Tracking','Mesure','التتبع'),t('Ads running on a pixel nobody has checked','Des publicités diffusées avec un pixel que personne n’a vérifié','إعلانات تعمل ببكسل لم يتحقق منه أحد'),t('Meta Pixel and Conversions API sending verified events, reported in GA4 and Looker Studio','Meta Pixel et Conversions API transmettent des événements vérifiés, suivis dans GA4 et Looker Studio','Meta Pixel وConversions API يرسلان أحداثاً تم التحقق منها، مع تقارير في GA4 وLooker Studio')],
   [t('Follow-up','Suivi des prospects','المتابعة'),t('Leads sitting in an inbox or a spreadsheet','Des prospects oubliés dans une boîte mail ou un tableur','عملاء محتملون عالقون في البريد أو جدول بيانات'),t('Leads routed into GoHighLevel or Mailchimp with automated email and SMS follow-up','Des prospects orientés vers GoHighLevel ou Mailchimp, avec un suivi automatisé par email et SMS','توجيه العملاء المحتملين إلى GoHighLevel أو Mailchimp مع متابعة آلية بالبريد والرسائل النصية')],
   [t('Content','Contenu','المحتوى'),t("Posting when there's time",'Publier quand le temps le permet','النشر عندما يتوفر الوقت'),t('A monthly calendar, a reusable content playbook and creative tested against results','Un calendrier mensuel, un guide éditorial réutilisable et des créations testées selon les résultats','تقويم شهري ودليل محتوى قابل لإعادة الاستخدام وتصاميم تُختبر بناءً على النتائج')],
  ],
  services:t('What I can take off your desk','Ce que je peux prendre en charge','ما يمكنني توليه عنك'),
  serviceCards:[
   {title:t('Paid social and acquisition','Publicité sociale et acquisition','الإعلانات الاجتماعية واكتساب العملاء'),copy:t('I build campaigns, test creative and connect conversion events to reporting. The work covers audiences, budgets, Pixel and CAPI.','Je crée les campagnes, teste les créations et relie les conversions aux rapports : audiences, budgets, Pixel et CAPI.','أبني الحملات وأختبر التصاميم وأربط أحداث التحويل بالتقارير، من الجمهور والميزانية إلى Pixel وCAPI.'),tools:['Meta Ads','TikTok Ads','LinkedIn Ads','Pinterest Ads','Pixel & CAPI']},
   {title:t('Social media management','Gestion des réseaux sociaux','إدارة وسائل التواصل الاجتماعي'),copy:t('I plan content, write and design posts, schedule publishing and manage daily community replies across the channels where your audience is active.','Je planifie le contenu, rédige et conçois les publications, organise leur diffusion et gère les échanges quotidiens avec votre communauté.','أخطط للمحتوى وأكتب وأصمم المنشورات وأنظم النشر وأدير تفاعل المجتمع يومياً عبر القنوات التي يوجد فيها جمهورك.'),tools:['Instagram','Facebook','TikTok','LinkedIn','Content calendars']},
   {title:t('Email marketing','Email marketing','التسويق عبر البريد الإلكتروني'),copy:t('I build newsletters and nurture sequences that turn a first enquiry into a useful next step, with segments, clear calls to action and reporting.','Je crée des newsletters et des séquences de suivi qui font avancer chaque demande, avec segmentation, appels à l’action clairs et rapports.','أبني نشرات وتسلسلات متابعة تحول الاستفسار الأول إلى خطوة مفيدة، مع تقسيم الجمهور ونداءات واضحة وتقارير.'),tools:['Email sequences','Mailchimp','Klaviyo','GoHighLevel','Email automation']},
   {title:t('CRM and marketing automation','CRM et automatisation marketing','إدارة علاقات العملاء وأتمتة التسويق'),copy:t('I connect lead capture, contact tagging and sales pipelines. Email and SMS workflows keep the next step clear for each lead.','Je relie la capture de prospects, les tags et les pipelines. Les séquences email et SMS organisent chaque étape du suivi.','أربط نماذج العملاء المحتملين بالوسوم ومسارات البيع. وتنظم تدفقات البريد والرسائل النصية الخطوة التالية لكل عميل.'),tools:['GoHighLevel','Meta Pixel','Klaviyo','Mailchimp']},
   {title:t('SEO, content and analytics','SEO, contenu et analyse','تحسين البحث والمحتوى والتحليلات'),copy:t('I plan search-led content and improve WordPress pages. GA4, Search Console and dashboards show what brings people in and what they do next.','Je planifie les contenus selon les recherches et améliore les pages WordPress. Les rapports montrent les sources de trafic et les actions qui suivent.','أخطط للمحتوى وفق نية البحث وأحسن صفحات WordPress. وتوضح تقارير GA4 وSearch Console مصادر الزيارات وما يفعله الزوار بعدها.'),tools:['GA4','Search Console','GTM','Looker Studio','WordPress']},
   {title:t('AI content and e-commerce','Contenu IA et e-commerce','المحتوى بالذكاء الاصطناعي والتجارة الإلكترونية'),copy:t('I build product listings, publishing workflows and creative assets. AI supports drafts and production, with review before publishing.','Je crée les fiches produits, les flux de publication et les visuels. L’IA accompagne la production, avec une vérification avant publication.','أبني قوائم المنتجات وتدفقات النشر والمواد الإبداعية. يدعم الذكاء الاصطناعي المسودات والإنتاج مع المراجعة قبل النشر.'),tools:['Shopify','Etsy','Canva','Replicate','Claude Code','Codex']},
  ],
  process:t('How I work','Ma méthode de travail','كيف أعمل'),steps:[
   [t('Audit','Audit','التدقيق'),t('I review your accounts, tracking, funnel and content, and send a short list of what to fix first.','J’examine vos comptes, le suivi, le tunnel et les contenus, puis je vous envoie une courte liste des corrections prioritaires.','أراجع حساباتك والتتبع ومسار التحويل والمحتوى، ثم أرسل قائمة مختصرة بأولويات الإصلاح.')],
   [t('Plan','Plan','التخطيط'),t('Channels, budget split, offers and a content calendar, agreed before anything goes live.','Canaux, répartition du budget, offres et calendrier éditorial sont validés avant toute mise en ligne.','أتفق معك على القنوات وتوزيع الميزانية والعروض وتقويم المحتوى قبل إطلاق أي شيء.')],
   [t('Launch','Lancement','الإطلاق'),t('Campaigns, landing pages, CRM flows and tracking built and tested.','Campagnes, pages d’atterrissage, flux CRM et suivi sont créés et testés.','أبني الحملات وصفحات الهبوط وتدفقات CRM والتتبع وأختبرها.')],
   [t('Optimize','Optimisation','التحسين'),t('Weekly reporting, creative and audience tests, and budget moved to what converts.','Rapports hebdomadaires, tests des créations et des audiences, puis réallocation du budget vers ce qui convertit.','تقارير أسبوعية واختبارات للتصاميم والجمهور، مع توجيه الميزانية نحو ما يحقق التحويلات.')],
  ],
  reviews:t('People I have worked with','Les personnes avec qui j’ai travaillé','آراء من عملت معهم'),previous:t('Previous review','Avis précédent','التقييم السابق'),next:t('Next review','Avis suivant','التقييم التالي'),
  about:t('A little about me','Quelques mots sur moi','نبذة عني'),bio:t('I’m El Mahdi Bouizmoune, a Digital Marketing Manager based in Safi, Morocco. I work across paid social, CRM automation, SEO and AI content, with more than eight years in digital marketing. I currently lead digital marketing at Bunchful Enterprise and am open to full-time roles and freelance projects worldwide.','Je suis El Mahdi Bouizmoune, Digital Marketing Manager basé à Safi, au Maroc. Je travaille sur la publicité sociale, l’automatisation CRM, le SEO et le contenu IA, avec plus de huit ans d’expérience. Je dirige actuellement le marketing digital chez Bunchful Enterprise et suis ouvert aux postes salariés et aux missions indépendantes dans le monde entier.','أنا المهدي بويزمون، مدير تسويق رقمي مقيم في آسفي بالمغرب. أعمل في الإعلانات الاجتماعية وأتمتة CRM وتحسين البحث والمحتوى بالذكاء الاصطناعي، بخبرة تتجاوز ثماني سنوات. أتولى حالياً التسويق الرقمي لدى Bunchful Enterprise، وأنا منفتح على الوظائف الدائمة والمشاريع المستقلة حول العالم.'),
  hire:t('Ways to work with me','Comment travailler avec moi','طرق العمل معي'),hireCards:[
   {title:t('Full-time role','Poste salarié','وظيفة بدوام كامل'),copy:t('Digital Marketing Manager roles, remote or relocation.','Postes de Digital Marketing Manager, à distance ou avec mobilité.','وظائف مدير تسويق رقمي، عن بُعد أو مع الانتقال.'),bullets:[t('Digital strategy and execution','Stratégie digitale et exécution','استراتيجية رقمية وتنفيذ'),t('Cross-channel reporting','Reporting multicanal','تقارير عبر القنوات'),t('English, French and Arabic','Anglais, français et arabe','الإنجليزية والفرنسية والعربية')]},
   {title:t('Freelance project','Mission indépendante','مشروع مستقل'),copy:t('Paid social, CRM setup or content systems, scoped per project.','Publicité sociale, configuration CRM ou systèmes de contenu, avec un périmètre défini.','إعلانات اجتماعية أو إعداد CRM أو أنظمة محتوى، بنطاق محدد لكل مشروع.'),bullets:[t('An agreed brief and deliverables','Un brief et des livrables convenus','موجز ومخرجات متفق عليها'),t('Campaigns and follow-up workflows','Campagnes et flux de suivi','حملات وتدفقات متابعة'),t('Documentation and handover','Documentation et passation','توثيق وتسليم')]},
   {title:t('Marketing audit','Audit marketing','تدقيق تسويقي'),copy:t('A review of your ads, tracking and funnel with a prioritized fix list.','Une analyse des publicités, du suivi et du tunnel avec une liste de corrections prioritaires.','مراجعة إعلاناتك والتتبع ومسار التحويل مع قائمة إصلاحات مرتبة حسب الأولوية.'),bullets:[t('Account and tracking review','Analyse des comptes et du suivi','مراجعة الحسابات والتتبع'),t('Funnel and content gaps','Lacunes du tunnel et du contenu','ثغرات مسار التحويل والمحتوى'),t('A practical action plan','Un plan d’action concret','خطة عمل عملية')]},
  ],
  faq:t('A few useful answers','Quelques réponses utiles','إجابات مفيدة'),faqs:[
   [t('Do you take full-time roles or freelance work?','Acceptez-vous les postes salariés et les missions indépendantes ?','هل تقبل الوظائف الدائمة أم العمل المستقل؟'),t("Both. I'm open to Digital Marketing Manager roles and to freelance projects, remote worldwide.",'Les deux. Je suis ouvert aux postes de Digital Marketing Manager et aux missions indépendantes, à distance dans le monde entier.','كلاهما. أنا منفتح على وظائف مدير تسويق رقمي والمشاريع المستقلة، عن بُعد حول العالم.')],
   [t('Which time zones can you cover?','Quels fuseaux horaires couvrez-vous ?','ما المناطق الزمنية التي يمكنك العمل معها؟'),t("I'm based in Morocco (GMT+1) and regularly work with US East Coast, UK and UAE teams, with overlap in US mornings.",'Je suis basé au Maroc (GMT+1) et travaille régulièrement avec des équipes de la côte Est américaine, du Royaume-Uni et des Émirats, avec un chevauchement le matin aux États-Unis.','أقيم في المغرب (GMT+1) وأعمل بانتظام مع فرق الساحل الشرقي الأمريكي والمملكة المتحدة والإمارات، مع ساعات مشتركة خلال الصباح في الولايات المتحدة.')],
   [t('Which platforms do you work in?','Sur quelles plateformes travaillez-vous ?','ما المنصات التي تعمل عليها؟'),''],
   [t('What languages do you work in?','Dans quelles langues travaillez-vous ?','بأي لغات تعمل؟'),t('English, French and Arabic.','Anglais, français et arabe.','الإنجليزية والفرنسية والعربية.')],
   [t('How do we start?','Comment commencer ?','كيف نبدأ؟'),t('Contact me through the form or by email. For freelance work I start with a short audit so we agree on priorities before any spend.','Contactez-moi via le formulaire ou par e-mail. Pour une mission indépendante, je commence par un audit rapide afin de convenir des priorités avant toute dépense.','تواصل معي عبر النموذج أو البريد الإلكتروني. أبدأ المشاريع المستقلة بتدقيق مختصر للاتفاق على الأولويات قبل أي إنفاق.')],
   [t('Can I see more work?','Puis-je voir d’autres réalisations ?','هل يمكنني مشاهدة المزيد من الأعمال؟'),t('Every case is on the Work page, and the full client list is on the Clients page.','Toutes les études de cas sont sur la page Réalisations, et la liste complète figure sur la page Clients.','كل دراسات الحالة متاحة في صفحة الأعمال، والقائمة الكاملة في صفحة العملاء.')],
  ],
  contact:t('Have a role or a project in mind?','Un poste ou un projet en tête ?','هل لديك وظيفة أو مشروع في ذهنك؟'),messageHint:t('Tell me about the role or project, your goals and your timeline.','Décrivez le poste ou le projet, vos objectifs et votre calendrier.','حدثني عن الوظيفة أو المشروع وأهدافك والجدول الزمني.'),
  strategy:t('Strategy','Stratégie','الاستراتيجية'),execution:t('Execution','Exécution','التنفيذ'),learning:t('Results and learnings','Résultats et enseignements','النتائج والدروس'),nextStep:t("What I’d do next",'La prochaine étape','ما سأفعله لاحقاً'),sector:t('Sector','Secteur','القطاع'),ownership:t('Relationship','Relation','نوع العلاقة'),timeline:t('Timeline','Période','الفترة'),channels:t('Channels','Canaux','القنوات'),stack:t('Stack','Outils','الأدوات'),
  listings:t('active listings','fiches actives','قائمة نشطة'),sales:t('sales','ventes','مبيعة'),etsyReviews:t('stars across 36 reviews','étoiles sur 36 avis','نجوم عبر 36 تقييماً'),since:t('Since 2024','Depuis 2024','منذ 2024'),
  workDescription:t('Paid social, CRM, content and e-commerce: eight projects, with my role, the decisions and the work delivered.','Publicité sociale, CRM, contenu et e-commerce : huit projets avec mon rôle, mes décisions et les livrables.','الإعلانات الاجتماعية وCRM والمحتوى والتجارة الإلكترونية: ثمانية مشاريع توضح دوري وقراراتي وما أنجزته.'),
  clientsDescription:t('Explore my freelance and agency engagements by industry, including real estate, retail, hospitality and professional services.','Découvrez mes missions indépendantes et en agence par secteur : immobilier, commerce, restauration et services professionnels.','استعرض مشاريعي المستقلة وعبر الوكالات حسب القطاع، ومنها العقارات والتجارة والضيافة والخدمات المهنية.'),
 };
}
