export type Testimonial = { quote: string; name: string; context: string; source: 'LinkedIn' | 'Fiverr' | 'Direct'; url: string; date?: string; featured: boolean; lead?: boolean };
export const testimonials: Testimonial[] = [
 {quote:"I wholeheartedly recommend Mahdi for his outstanding social media management skills. His expertise helped us increase our following by hundreds of thousands during our partnership of over five years. Mahdi's excellent communication and collaborative approach made working with him a breeze.",name:'Dione Letitia Masters',context:'Speaker & Athlete Ambassador, Strongman Corporation',source:'LinkedIn',url:'https://www.linkedin.com/in/mahdi-bouizmoune/',date:'2024-09-02',featured:true,lead:true},
 {quote:"It was a pleasure working with Mahdi. He's a creative person, good communicator and definitely will work with him again",name:'cmansar',context:'Netherlands · Social Media Management',source:'Fiverr',url:'https://www.fiverr.com/pro5services',featured:true},
 {quote:"His creativity and attention to detail transformed my ideas into eye-catching posts that perfectly capture my brand's essence.",name:'marcusringler',context:'United Arab Emirates · Repeat client',source:'Fiverr',url:'https://www.fiverr.com/pro5services',featured:true},
 {quote:'Always goes above and beyond! Love working with him and you will too!',name:'lpt100',context:'United States · Shopify store management · Repeat client',source:'Fiverr',url:'https://www.fiverr.com/pro5services',featured:true},
 {quote:'He was professional, creative and delivered on time. He created a stunning website, a catchy logo and a powerful social media campaign for me. He also gave me useful tips and feedback along the way.',name:'marcusringler',context:'United Arab Emirates · Repeat client',source:'Fiverr',url:'https://www.fiverr.com/pro5services',featured:false},
 {quote:'I can recommend him to others, good problem solver and answers messages in time and adapts fast changes if needed.',name:'marcusringler',context:'United Arab Emirates · Repeat client',source:'Fiverr',url:'https://www.fiverr.com/pro5services',featured:false},
 {quote:'well done, got what i was looking for and was well accountable of his work. thanks',name:'oneweare',context:'United States · Shopify store management',source:'Fiverr',url:'https://www.fiverr.com/pro5services',featured:false},
 {quote:'Mehdi is gracious & easy to work with. I highly recommend Pro 5 Services.',name:'nidalcool',context:'United Arab Emirates',source:'Fiverr',url:'https://www.fiverr.com/pro5services',featured:true},
 {quote:'Great as always. Refined the approach according to feedback and follower behavior. Highly recommend.',name:'krestonkent',context:'United States',source:'Fiverr',url:'https://www.fiverr.com/pro5services',featured:true},
 {quote:'Mahdi is a great researcher and is pretty creative when it comes to generating new content. […] Still a great value and he did a nice job.',name:'liquidthorium',context:'United States',source:'Fiverr',url:'https://www.fiverr.com/pro5services',featured:false},
 {quote:'Mahdi has done a great job! I will continue working with him. Thank you!',name:'aymee007',context:'United States',source:'Fiverr',url:'https://www.fiverr.com/pro5services',featured:true},
 {quote:'Great as always. I have been working with Mahdi for about 5 months now. He always delivers his promises.',name:'gianluigiporto',context:'United States',source:'Fiverr',url:'https://www.fiverr.com/pro5services',featured:true},
];
