import Image from 'next/image';
import { ArrowDown, ArrowUpRight, Asterisk } from 'lucide-react';
const work = [
  { slug:'akam', title:'A place to call home.', client:'AKAM · NEW YORK', type:'Social strategy / Content / Paid media', image:'akam.png', theme:'blue' },
  { slug:'gourmet-gather', title:'From inspiration to discovery.', client:'GOURMET GATHER', type:'SEO / Pinterest / Automation', image:'gourmet.png', theme:'green' },
  { slug:'bunchful', title:'Giving a purpose its voice.', client:'BUNCHFUL ENTERPRISE', type:'Brand storytelling / Content / SEO', image:'bunchful.png', theme:'pink' },
];
export default function Home(){return <>
  <header className="header wrap"><a className="wordmark" href="/" aria-label="Mahdi B. home">mahdi b<span>.</span></a><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#expertise">Expertise</a><a href="#about">About</a></nav><a className="nav-contact" href="#contact">Let’s talk <ArrowUpRight size={17}/></a></header>
  <main id="main">
    <section className="hero wrap"><div className="eyebrow"><span className="dot"/> INDEPENDENT DIGITAL MARKETER & AUTOMATION BUILDER</div><h1>Marketing that<br/><span className="orange">connects.</span><br/>Systems that <span className="serif">convert.</span></h1><div className="hero-bottom"><div className="hero-intro"><p>I’m El Mahdi Bouizmoune. I connect content, paid media, and smart automation to help brands turn attention into action.</p><a className="text-link" href="#work">Explore my work <ArrowDown size={18}/></a></div><div className="hero-note"><Asterisk size={56} strokeWidth={1.4}/><p>Strategy meets execution.<br/>Morocco, working worldwide.</p></div></div></section>
    <div className="discipline-strip" aria-label="Specialties"><span>CONTENT</span><Asterisk/><span>PAID MEDIA</span><Asterisk/><span>CRM & AUTOMATION</span><Asterisk/><span>AI SYSTEMS</span><Asterisk/></div>
    <section className="work-section wrap section" id="work"><div className="section-top"><p className="eyebrow">01 / SELECTED WORK</p><p>A few brands. Different challenges.<br/>The same hands-on approach.</p></div><h2>Good work.<br/><span className="serif">Real intention.</span></h2><div className="work-grid">{work.map((item,i)=><a className={`work-card card-${i}`} key={item.slug} href={`/work/${item.slug}`}><div className={`work-image ${item.theme}`}><span className="card-index">0{i+1}</span><Image unoptimized src={`/assets/${item.image}`} alt={`${item.client} social campaign creative`} width={864} height={864} loading="lazy"/><span className="round-arrow"><ArrowUpRight/></span></div><div className="work-caption"><span className="eyebrow">{item.client}</span><h3>{item.title}</h3><p>{item.type}</p></div></a>)}</div><div className="systems-teaser"><div><p className="eyebrow">BEYOND THE CAMPAIGN</p><h3>I also build the systems<br/>behind the growth.</h3></div><div className="system-links"><a href="/work/content-studio"><span>AI Content Studio<small>Research → Create → Publish</small></span><ArrowUpRight/></a><a href="/work/skyrocket-your-biz"><span>Skyrocket Your Biz<small>Lead capture → Nurture → Conversion</small></span><ArrowUpRight/></a><a href="/work/strongman"><span>Strongman Corporation<small>Content → Community → Events</small></span><ArrowUpRight/></a></div></div></section>
    <section className="expertise" id="expertise"><div className="wrap section"><div className="section-top"><p className="eyebrow">02 / HOW I HELP</p><p>From the first impression<br/>to the next customer.</p></div><h2>The whole picture.<br/><span className="serif">Every moving part.</span></h2><div className="service-list">{[
      ['01','Content & social','A consistent voice. A reason to engage.','Social strategy, content calendars, copywriting, short-form video, and community management.'],
      ['02','Paid media & growth','Get in front of the right people.','Meta, TikTok, Pinterest, and LinkedIn campaigns, with creative testing and conversion tracking.'],
      ['03','CRM & automation','Make the follow-up work for you.','GoHighLevel funnels, lead pipelines, email sequences, and customer journeys that keep moving.'],
      ['04','SEO & AI systems','Build a smarter way to grow.','Search-led content, WordPress optimization, analytics, and AI-assisted publishing workflows.']
    ].map(([num,title,tagline,description])=><article className="service" key={num}><span className="service-num">{num}</span><h3>{title}</h3><div><h4>{tagline}</h4><p>{description}</p></div><ArrowUpRight className="service-arrow"/></article>)}</div></div></section>
    <section className="about wrap section" id="about"><div><p className="eyebrow">03 / A LITTLE ABOUT ME</p><h2>A strategist’s mind.<br/>A builder’s <span className="serif">instinct.</span></h2><div className="about-stat"><span>8+</span><p>years connecting<br/>brands and people</p></div></div><div className="about-copy"><p className="lead">I like understanding how things connect. The story that starts a conversation. The campaign that brings someone in. The workflow that takes care of what happens next.</p><p>I’m a trilingual digital marketer based in Safi, Morocco. Since 2018, I’ve worked with organizations across real estate, fitness, food, and social impact—bringing strategy, creative work, and the technical details together.</p><p>Alongside client work, I build my own content and automation tools. It keeps me curious, practical, and close to the work.</p><div className="languages"><span>English</span><span>Français</span><span lang="ar" dir="rtl">العربية</span></div><a className="text-link" href="https://www.linkedin.com/in/mahdibouizmoune" target="_blank" rel="noreferrer">More about my experience <ArrowUpRight size={18}/></a></div></section>
    <section className="contact" id="contact"><div className="wrap"><div className="section-top"><p className="eyebrow">HAVE SOMETHING IN MIND?</p><p>Let’s make the next move count.</p></div><a className="contact-title" href="mailto:mahdi.bouizmoune@gmail.com">Let’s build<br/><span className="serif">what’s next.</span><ArrowUpRight aria-hidden="true"/></a><div className="contact-bottom"><a href="mailto:mahdi.bouizmoune@gmail.com">mahdi.bouizmoune@gmail.com</a><div><a href="https://www.linkedin.com/in/mahdibouizmoune" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://www.fiverr.com/pro5services" target="_blank" rel="noreferrer">Fiverr ↗</a></div></div></div></section>
  </main><footer className="wrap footer"><a className="wordmark" href="/">mahdi b<span>.</span></a><span>© {new Date().getFullYear()} El Mahdi Bouizmoune</span><a href="#main">Back to top ↑</a></footer>
</>}

