import {Header,Footer,Contact} from './portfolio-shell';
import {WorkImage} from './work-image';
import {dictionary,localizePath,Text,type Locale} from '../lib/i18n';
import {SITE} from '../lib/site';
import {siteUrl} from '../lib/seo';
export function CaseStudy({slug,locale='en'}:{slug:string;locale?:Locale}){
 const d=dictionary(locale),p=d.work[slug as keyof typeof d.work],slugs=Object.keys(d.work),next=slugs[(slugs.indexOf(slug)+1)%slugs.length],path=(p:string)=>localizePath(p,locale);
 const schema=[{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:d.a11y.home,item:siteUrl+path('/')},{'@type':'ListItem',position:2,name:p.name,item:siteUrl+path('/work/'+slug)}]},{'@context':'https://schema.org','@type':'CreativeWork',name:p.name,description:p.intro,inLanguage:locale,url:siteUrl+path('/work/'+slug),author:{'@type':'Person',name:SITE.name,url:siteUrl+path('/')}}];
 return <><Header locale={locale} currentPath={'/work/'+slug}/><main id="main" tabIndex={-1}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/>
 <section className="case-header wrap"><a className="text-link" href={path('/#work')}><span className="icon-directional" aria-hidden="true">← </span>{d.caseStudy.allWork}</a><p className="eyebrow"><Text locale={locale}>{p.name+' / '+p.category}</Text></p><h1>{p.title}</h1><div className="case-intro"><p><Text locale={locale}>{p.intro}</Text></p></div></section>
 <div className="case-body wrap section"><aside><p className="eyebrow">{d.caseStudy.role}</p><p className="case-role">{p.role}</p>{p.period&&<p className="case-period"><Text locale={locale}>{p.period}</Text></p>}<div className="tool-tags" aria-label={d.a11y.tools}>{p.tools.map(t=><bdi key={t}>{t}</bdi>)}</div></aside>
 <div className="case-story"><section><h2>{d.caseStudy.problem}</h2><p><Text locale={locale}>{p.context}</Text></p></section><section><h2>{d.caseStudy.actions}</h2><ul>{p.approach.map(a=><li key={a}><Text locale={locale}>{a}</Text></li>)}</ul></section><section><h2>{d.caseStudy.result}</h2><p><Text locale={locale}>{p.delivered}</Text></p><div className="metric-grid">{p.metrics.map((m,i)=><div className="metric" key={i}><strong><bdi>{m.value}</bdi></strong><p>{m.label}</p><small>{m.timeframe}</small></div>)}</div></section><section><h2>{d.caseStudy.proof}</h2>{p.proof.src?<figure><WorkImage name={p.proof.src} alt={d.caseStudy.proofAlt+' · '+p.name}/><figcaption>{p.proof.caption}</figcaption></figure>:<div className="proof-slot">{p.proof.caption}</div>}{p.proof.href&&<a href={p.proof.href} target="_blank" rel="noopener noreferrer">{d.directory.website}<span className="sr-only"> ({d.a11y.openInNewTab})</span></a>}</section></div></div>
 <div className="wrap case-next"><span className="eyebrow">{d.caseStudy.next}</span><a href={path('/work/'+next)}><Text locale={locale}>{d.work[next as keyof typeof d.work].name}</Text><span className="icon-directional" aria-hidden="true"> ↗</span></a></div><Contact locale={locale}/></main><Footer locale={locale}/></>;
}
