import {Header,Footer,Contact,ExternalLink} from './portfolio-shell';
import {CaseCover} from './work-grid';
import {QuoteCard} from './home-sections';
import {getCase,caseOrder,type CaseSlug} from '../content/cases';
import {growth} from '../content/growth';
import {dictionary,localizePath,Text,type Locale} from '../lib/i18n';
import {SITE} from '../lib/site';
import {siteUrl} from '../lib/seo';
export function CaseStudy({slug,locale='en'}:{slug:string;locale?:Locale}){
 const p=getCase(slug as CaseSlug,locale),g=growth(locale),d=dictionary(locale),path=(p:string)=>localizePath(p,locale),next=getCase(caseOrder[(caseOrder.indexOf(slug as CaseSlug)+1)%caseOrder.length],locale);
 const schema=[{'@context':'https://schema.org','@type':'CreativeWork',name:p.title,description:p.summary,inLanguage:locale,url:siteUrl+path('/work/'+slug),author:{'@type':'Person',name:SITE.name,url:siteUrl+path('/')}},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:g.allWork,item:siteUrl+path('/work')},{'@type':'ListItem',position:2,name:p.client,item:siteUrl+path('/work/'+slug)}]}];
 return <><Header locale={locale} currentPath={'/work/'+slug}/><main id="main" tabIndex={-1} data-case-slug={slug}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><section className="case-header wrap section"><a className="text-link" href={path('/work')}><span className="icon-directional" aria-hidden="true">←</span> {g.allWork}</a><p className="eyebrow"><bdi>{p.client}</bdi></p><h1>{p.title}</h1><p className="lead">{p.summary}</p><dl className="case-meta">{[[p.client,g.client],[p.sector,g.sector],[g[p.ownership],g.ownership],[p.role,d.caseStudy.role],[p.timeline,g.timeline],[p.channels.join(' · '),g.channels],[p.stack.join(' · '),g.stack]].filter(([v])=>v).map(([value,label])=><div key={label}><dt>{label}</dt><dd><Text locale={locale}>{value}</Text></dd></div>)}</dl>{p.metrics.length>0&&<div className="metric-grid">{p.metrics.slice(0,3).map(m=><article className="metric" key={m.label}><strong className="stat-number"><bdi>{m.value}</bdi></strong><p>{m.label}</p><small>{m.timeframe}</small></article>)}</div>}<CaseCover project={p} locale={locale}/></section><div className="wrap case-story"><section><h2>{d.caseStudy.problem}</h2><p>{p.challenge}</p></section><section><h2>{g.strategy}</h2><p>{p.strategy}</p></section><section><h2>{g.execution}</h2><ul>{p.execution.map(item=><li key={item}><Text locale={locale}>{item}</Text></li>)}</ul></section><section><h2>{g.learning}</h2>{p.results.map(r=><p key={r}>{r}</p>)}<h3>{g.nextStep}</h3><p>{p.nextStep}</p></section>{p.quote&&<QuoteCard quote={p.quote} locale={locale} lead/>}{p.links.length>0&&<section><h2>{d.caseStudy.proof}</h2><div className="actions">{p.links.map(l=><ExternalLink className="button outline" key={l.url} href={l.url} locale={locale}>{l.label} ↗</ExternalLink>)}</div></section>}</div><section className="section wrap"><p className="eyebrow">{d.caseStudy.next}</p><a className="next-case" href={path('/work/'+next.slug)}><h2>{next.title}</h2><span className="icon-directional" aria-hidden="true">↗</span></a></section><Contact locale={locale}/></main><Footer locale={locale}/></>;
}
