import {Header,Footer,Contact} from './portfolio-shell';
import {dictionary,localizePath,Text,type Locale,type Dictionary} from '../lib/i18n';
export function LogoWall({d}:{d:Dictionary}){return <section className="logo-section wrap"><h2>{d.directory.logoTitle}</h2><div className="logo-wall">{d.logos.map(l=><div className="logo-cell" key={l.name}>{l.src?
 // oxlint-disable-next-line next/no-img-element -- Approved logos can be supplied without changing layout.
 <img src={l.src} width={180} height={80} alt={l.name} loading="lazy" decoding="async"/>:<><bdi>{l.name}</bdi><small>{d.directory.logoPending}</small></>}</div>)}</div></section>}
export function Testimonials({d}:{d:Dictionary}){return <section className="wrap section"><h2>{d.directory.testimonials}</h2><div className="testimonial-grid">{d.testimonials.map((t,i)=><figure className="testimonial" key={i}><blockquote><p>{t.quote}</p></blockquote><figcaption>{t.name}<br/>{t.role}, {t.company}{t.href&&<a href={t.href} target="_blank" rel="noopener noreferrer">{d.directory.website}<span className="sr-only"> ({d.a11y.openInNewTab})</span></a>}</figcaption></figure>)}</div></section>}
export function ClientsDirectory({locale='en'}:{locale?:Locale}){
 const d=dictionary(locale),path=(p:string)=>localizePath(p,locale),sectors=[...new Set(d.clients.map(c=>c.sector))];
 return <><Header locale={locale} currentPath="/clients"/><main id="main" tabIndex={-1}><section className="wrap directory-header"><a className="text-link" href={path('/#work')}><span className="icon-directional" aria-hidden="true">← </span>{d.directory.back}</a><p className="eyebrow">{d.sections.clients}</p><h1>{d.directory.headline}<br/><span className="serif">{d.directory.accent}</span></h1><p className="section-intro">{d.directory.intro}</p></section><LogoWall d={d}/><nav className="sector-nav wrap" aria-label={d.directory.industries}>{sectors.map((s,i)=><a key={s} href={'#sector-'+i}>{s}</a>)}</nav><div className="wrap directory">{sectors.map((s,i)=><section id={'sector-'+i} key={s} className="sector"><h2>{s}</h2><ul>{d.clients.filter(c=>c.sector===s).map(c=><li key={c.name}><div><h3><Text locale={locale}>{c.name}</Text></h3><p><Text locale={locale}>{c.context}</Text></p><p className="client-scope"><Text locale={locale}>{c.scope}</Text></p><p className="client-tools"><Text locale={locale}>{c.tools}</Text></p></div>{'caseSlug'in c&&c.caseSlug?<a href={path('/work/'+c.caseSlug)} aria-label={c.name+' · '+d.directory.caseStudy}>{d.directory.caseStudy}<span className="icon-directional" aria-hidden="true"> ↗</span></a>:'href'in c&&c.href?<a href={c.href} target="_blank" rel="noopener noreferrer">{d.directory.website}<span className="sr-only"> · {c.name} ({d.a11y.openInNewTab})</span><span className="icon-directional" aria-hidden="true"> ↗</span></a>:null}</li>)}</ul></section>)}</div><section className="wrap directory-note"><h2>{d.directory.crmTitle}</h2><p><Text locale={locale}>{d.directory.crm}</Text></p></section><section className="wrap directory-note"><h2>{d.directory.employmentTitle}</h2><p><Text locale={locale}>{d.directory.employment}</Text></p><a className="text-link" href={path('/#experience')}>{d.nav.experience}</a></section><Testimonials d={d}/><Contact locale={locale}/></main><Footer locale={locale}/></>;
}
