/* oxlint-disable next/no-img-element -- Local compressed portraits with explicit dimensions and responsive sources. */
import {growth} from '../content/growth';
import {proof} from '../content/proof';
import {testimonials,type Testimonial} from '../content/testimonials';
import {caseOrder} from '../content/cases';
import {dictionary,localizePath,Text,type Locale} from '../lib/i18n';
import {SITE} from '../lib/site';
import {ContactLink,CvLink,ExternalLink} from './portfolio-shell';
import {ReviewCarousel,FAQAccordion} from './growth-controls';
import {WorkGrid} from './work-grid';
type Props={locale:Locale};
export function Portrait({hero=false}:{hero?:boolean}){return <img src="/assets/mahdi-portrait-800.webp" srcSet="/assets/mahdi-portrait-400.webp 400w, /assets/mahdi-portrait-800.webp 800w, /assets/mahdi-portrait-1200.webp 1200w" sizes={hero?'(max-width: 767px) 280px, (max-width: 1100px) 34vw, 400px':'(max-width: 767px) 180px, 280px'} width={800} height={800} alt={SITE.name} loading={hero?'eager':'lazy'} fetchPriority={hero?'high':'auto'} decoding="async"/>;}
export function FiverrBadge({locale}:Props){return <ExternalLink className="rating-badge" href={SITE.social.fiverr} locale={locale}><span aria-hidden="true" className="stars">★★★★★</span> <bdi>{growth(locale).rating}</bdi></ExternalLink>;}
export function Hero({locale}:Props){const g=growth(locale);return <section className="hero hero-band"><div className="hero-copy"><p className="eyebrow hero-identity"><bdi>{SITE.name}</bdi> · <FiverrBadge locale={locale}/></p><h1>{g.hero}</h1><p className="hero-subline"><Text locale={locale}>{g.subline}</Text></p><dl className="brief-meta"><div><dt>{g.roleLabel}</dt><dd><Text locale={locale}>{SITE.role}</Text></dd></div><div><dt>{g.basedLabel}</dt><dd><Text locale={locale}>{g.basedShort}</Text></dd></div><div><dt>{g.statusLabel}</dt><dd>{g.statusOpen}</dd></div></dl><div className="actions"><ContactLink locale={locale}/><a className="button outline" href="#work">{g.seeWork} <span aria-hidden="true">↓</span></a></div><dl className="ledger"><div className="ledger-row"><dd>{proof.years}</dd><dt>{g.yearsLabel}</dt></div><div className="ledger-row"><dd>{proof.engagements}</dd><dt>{g.engagementsLabel}</dt></div><div className="ledger-row"><dd>{proof.reach}</dd><dt>{g.reachLabel}</dt></div></dl></div><figure className="hero-portrait"><Portrait hero/><span className="stamp" aria-hidden="true">{g.stamp}</span><figcaption><span>{g.now}</span><span>{g.location}</span></figcaption></figure></section>;}
const brands=['AKAM','Bunchful Enterprise','Generation Atomic','Strongman Corporation','Fresh Body','Excilify','PRIMO','Raffaella','RetroChic'];
export function LogoStrip({locale}:Props){return <section className="brands-section" aria-label={growth(locale).brands}><div className="wrap"><p className="eyebrow">{growth(locale).brands}</p>{/* oxlint-disable-next-line jsx-a11y/no-noninteractive-tabindex -- Focusable so keyboard/AT users can pause the auto-scrolling marquee (WCAG 2.2.2), matching the existing :hover/:focus-within pause rule in globals.css. */}<div className="brand-marquee" tabIndex={0}><div className="brand-track"><div>{brands.map(n=><bdi key={n}>{n}</bdi>)}</div><div aria-hidden="true">{brands.map(n=><bdi key={n}>{n}</bdi>)}</div></div></div></div></section>;}
export function SelectedWork({locale}:Props){const g=growth(locale);return <section className="section selected-work-band" id="work"><div className="wrap"><div className="section-heading" data-reveal><h2>{g.work}</h2><a className="text-link" href={localizePath('/work',locale)}>{g.allWork} <span className="icon-directional" aria-hidden="true">↗</span></a></div><WorkGrid locale={locale} slugs={caseOrder.slice(0,6)}/></div></section>;}
export function BeforeAfter({locale}:Props){const g=growth(locale);return <section className="section approach-section" id="approach"><div className="wrap"><h2 data-reveal>{g.approach}</h2><div className="changes">{g.changes.map(([label,before,after])=><article className="change-row" key={label} data-reveal><h3>{label}</h3><div><span className="eyebrow">{g.before}</span><p>{before}</p></div><div className="after"><span className="eyebrow">{g.after}</span><p><Text locale={locale}>{after}</Text></p></div></article>)}</div></div></section>;}
export function Services({locale}:Props){const g=growth(locale);return <section className="section wrap" id="services"><p className="eyebrow">{g.nav[1]}</p><h2 data-reveal>{g.services}</h2><div className="services-grid">{g.serviceCards.map((s,i)=><article className="service-card" key={s.title} data-reveal><span className="service-number mono">0{i+1}</span><h3>{s.title}</h3><p>{s.copy}</p><div className="chips">{s.tools.map(t=><bdi key={t}>{t}</bdi>)}</div></article>)}</div></section>;}
export function Process({locale}:Props){const g=growth(locale);return <section className="section process-section" id="process"><div className="wrap"><h2 data-reveal>{g.process}</h2><ol className="process-grid">{g.steps.map(([title,copy],i)=><li key={title} data-reveal><span className="step-number mono">0{i+1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></div></section>;}
export function QuoteCard({quote,locale,lead=false}:{quote:Testimonial;locale:Locale;lead?:boolean}){const g=growth(locale);return <figure className={'quote-card '+(lead?'lead-quote':'')}><ExternalLink href={quote.url} locale={locale} className="quote-source">{quote.source==='LinkedIn'?g.recommendation:quote.source}</ExternalLink><blockquote lang="en" dir="ltr"><p>{quote.quote}</p></blockquote><figcaption lang="en" dir="ltr"><strong>{quote.name}</strong><span>{quote.context}</span></figcaption></figure>;}
export function Reviews({locale}:Props){const g=growth(locale),seen=new Set<string>();const featured=testimonials.filter(q=>{if(!q.featured||q.lead||seen.has(q.name))return false;seen.add(q.name);return true;});return <section className="section wrap" id="reviews"><p className="eyebrow">{g.nav[3]}</p><h2 data-reveal>{g.reviews}</h2><div data-reveal><QuoteCard quote={testimonials[0]} locale={locale} lead/></div><ReviewCarousel previous={g.previous} next={g.next}>{featured.map(q=><QuoteCard key={q.name} quote={q} locale={locale}/>)}</ReviewCarousel><FiverrBadge locale={locale}/></section>;}
export function About({locale}:Props){const g=growth(locale),d=dictionary(locale);return <section className="section about-section" id="about"><div className="wrap"><div className="about-intro"><figure className="about-portrait"><Portrait/></figure><div><p className="eyebrow">{g.about}</p><h2><bdi>{SITE.name}</bdi></h2><p className="lead">{g.bio}</p><div className="chips languages"><span lang="en">English</span><span lang="fr">Français</span><span lang="ar">العربية</span></div><CvLink locale={locale}/></div></div><div id="experience" className="timeline"><h3 data-reveal>{d.nav.experience}</h3>{d.experience.map(e=><article key={e.company} data-reveal><p className="mono"><Text locale={locale}>{e.period}</Text></p><div><h4><Text locale={locale}>{e.company}</Text></h4><p>{e.role}</p><small><Text locale={locale}>{e.location}</Text></small></div><p>{e.copy}</p></article>)}</div></div></section>;}
export function WaysToWork({locale}:Props){const g=growth(locale);return <section className="section wrap" id="hire"><h2 data-reveal>{g.hire}</h2><div className="hire-grid">{g.hireCards.map((c,i)=><article className="hire-card" key={c.title} data-reveal><h3>{c.title}</h3><p>{c.copy}</p><ul>{c.bullets.map(b=><li key={b}>{b}</li>)}</ul>{i===0?<CvLink locale={locale}/>:<ContactLink locale={locale}/>}</article>)}</div></section>;}
export function FAQ({locale}:Props){const g=growth(locale),d=dictionary(locale);const items=g.faqs.map(([question,answer],i)=>({question,answer:i===2?g.serviceCards.flatMap(c=>c.tools).join(', '):answer}));const schema={'@context':'https://schema.org','@type':'FAQPage',mainEntity:items.map(q=>({'@type':'Question',name:q.question,acceptedAnswer:{'@type':'Answer',text:q.answer}}))};return <section className="section faq-section" id="faq"><div className="wrap"><h2 data-reveal>{g.faq}</h2><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><FAQAccordion items={items.map((q,i)=>({question:q.question,answer:<><p><Text locale={locale}>{q.answer}</Text></p>{i===5&&<p className="actions"><a href={localizePath('/work',locale)}>{g.allWork}</a><a href={localizePath('/clients',locale)}>{d.nav.clients}</a></p>}</>}))}/></div></section>;}
