import {dictionary,localizePath,type Locale} from '../lib/i18n';
import {growth} from '../content/growth';
import {SITE} from '../lib/site';
import {ContactForm} from './contact-form';
import {MobileMenu} from './growth-controls';
import cvFiles from '../lib/cv-files.json';
export function ExternalLink({href,children,locale,className}:{href:string;children:React.ReactNode;locale:Locale;className?:string}){return <a className={className} href={href} target="_blank" rel="noopener noreferrer">{children}<span className="sr-only"> ({dictionary(locale).a11y.openInNewTab})</span></a>;}
export function CvLink({locale}:{locale:Locale}){const d=dictionary(locale),fallback=locale!=='en'&&cvFiles[locale]===SITE.cv.en;return <a className="button primary cv-link" href={cvFiles[locale]} download="El-Mahdi-Bouizmoune-CV.pdf" data-analytics="cv_download" data-analytics-locale={locale}>{fallback?(locale==='ar'?'السيرة الذاتية (EN)':'CV (EN)'):d.nav.downloadCv}</a>;}
export function ContactLink({locale}:{locale:Locale}){return <a className="button primary" href="#contact" data-analytics="contact_click">{growth(locale).book}<span aria-hidden="true">↓</span></a>;}
export function Header({locale='en',currentPath='/'}:{locale?:Locale;currentPath?:string}){
 const d=dictionary(locale),g=growth(locale),ids=['work','services','process','reviews','about'];
 const nav=<nav className="main-nav" aria-label={d.a11y.mainNavigation}>{ids.map((id,i)=><a href={localizePath('/#'+id,locale)} key={id}>{g.nav[i]}</a>)}</nav>;
 const languages=<nav className="language-switcher" aria-label={d.a11y.languageSwitcher}>{(['en','fr','ar'] as const).map(l=><a key={l} href={localizePath(currentPath,l)} lang={l} dir={l==='ar'?'rtl':'ltr'} aria-current={l===locale?'true':undefined} data-locale={l}>{l==='ar'?'العربية':l.toUpperCase()}</a>)}</nav>;
 return <header className="site-header" id="top" tabIndex={-1}><div className="header wrap"><a className="wordmark" href={localizePath('/',locale)} aria-label={SITE.name+' · '+d.a11y.home}><bdi>mahdi b<span>.</span></bdi></a><div className="desktop-navigation">{nav}{languages}<CvLink locale={locale}/></div><ContactLink locale={locale}/><MobileMenu label={g.menu} close={g.close}>{nav}{languages}<CvLink locale={locale}/></MobileMenu></div></header>;
}
export function Footer({locale='en'}:{locale?:Locale}){const d=dictionary(locale);return <footer className="footer-shell"><div className="wrap footer"><div><strong><bdi>{SITE.name}</bdi></strong><p>{d.hero.eyebrow} · {d.footer.location.split(' · ').at(-1)}</p></div><nav aria-label={d.a11y.footerNavigation}><a href={localizePath('/work',locale)}>{d.nav.work}</a><a href={localizePath('/clients',locale)}>{d.nav.clients}</a><a href={localizePath('/#about',locale)}>{d.nav.about}</a></nav><div className="social-links">{Object.entries(SITE.social).map(([name,href])=><ExternalLink key={name} href={href} locale={locale}>{name==='linkedin'?'LinkedIn':name==='github'?'GitHub':'Fiverr'}</ExternalLink>)}</div><CvLink locale={locale}/><div className="footer-bottom"><span>© {new Date().getFullYear()} <bdi>{SITE.name}</bdi></span><a href="#top" data-back-top>{d.footer.backToTop} ↑</a></div></div></footer>;}
export function Contact({locale='en'}:{locale?:Locale}){const d=dictionary(locale),g=growth(locale);return <section className="contact section" id="contact"><div className="wrap contact-layout"><div><p className="eyebrow">{d.footer.book}</p><h2>{g.contact}</h2><p>{d.footer.intro}</p><div className="actions"><ContactLink locale={locale}/><CvLink locale={locale}/></div><a className="email-fallback" href={'mailto:'+SITE.email} data-analytics="email_click"><bdi>{SITE.email}</bdi></a></div><div><ContactForm copy={d.form} locale={locale}/></div></div></section>;}
