import type {ReactNode} from 'react';
import {getCase,caseOrder,filterIds,type Case,type CaseSlug,type Filter} from '../content/cases';
import {growth} from '../content/growth';
import {dictionary,localizePath,type Locale,Text} from '../lib/i18n';
import {WorkImage} from './work-image';
import {WorkFilters} from './growth-controls';
import {Header,Footer,Contact} from './portfolio-shell';
export function CaseCover({project,locale,grid=false}:{project:Case;locale:Locale;grid?:boolean}){const showImage=!grid&&project.images.length>0;return <div className={'case-cover '+(showImage?'has-image':'generated-cover')}>{showImage?<WorkImage name={project.images[0].src} alt={project.client+' · '+project.images[0].caption}/>:<><span className="mono cover-sector"><Text locale={locale}>{project.sector}</Text></span><strong><bdi>{project.client}</bdi></strong><div className="chips">{project.channels.map(c=><bdi key={c}>{c}</bdi>)}</div></>}</div>;}
export type BonusClient={name:string;sector:string;title:string;tools:string[];href:string;external?:boolean;filters:Filter[]};
export type GridEntry={kind:'case';slug:CaseSlug}|{kind:'client';client:BonusClient};
export function WorkGrid({locale,entries=caseOrder.map(slug=>({kind:'case',slug}) as GridEntry)}:{locale:Locale;entries?:GridEntry[]}){const g=growth(locale),d=dictionary(locale);const cards:{slug:string;filters:Filter[];node:ReactNode}[]=entries.map((entry,i)=>{if(entry.kind==='case'){const p=getCase(entry.slug,locale);return {slug:entry.slug,filters:p.filters,node:<article className="work-card" data-reveal><a href={localizePath('/work/'+entry.slug,locale)}><CaseCover project={p} locale={locale} grid/><div className="work-caption"><div className="chips"><span>{p.sector}</span></div><h3>{p.title}</h3>{p.metrics.length>0&&<p className="case-card-metric"><bdi>{p.metrics[0].value}</bdi> {p.metrics[0].label}</p>}<div className="chips muted-chips">{p.channels.map(c=><bdi key={c}>{c}</bdi>)}</div><span className="read-case">{g.readCase} <span className="icon-directional" aria-hidden="true">↗</span></span></div></a></article>};}const c=entry.client;return {slug:'client-'+i,filters:c.filters,node:<article className="work-card" data-reveal><a href={c.href} target={c.external?'_blank':undefined} rel={c.external?'noopener noreferrer':undefined}><div className="case-cover generated-cover"><span className="mono cover-sector">{c.sector}</span><strong><bdi>{c.name}</bdi></strong><div className="chips">{c.tools.map(t=><bdi key={t}>{t}</bdi>)}</div></div><div className="work-caption"><div className="chips"><span>{c.sector}</span></div><h3>{c.title}</h3><div className="chips muted-chips">{c.tools.map(t=><bdi key={t}>{t}</bdi>)}</div><span className="read-case">{c.external?d.directory.website:g.seeAllClients} <span className="icon-directional" aria-hidden="true">↗</span></span>{c.external&&<span className="sr-only"> ({d.a11y.openInNewTab})</span>}</div></a></article>};});return <WorkFilters filters={filterIds.map((id,i)=>({id,label:g.filters[i]}))} cards={cards}/>;}
export function WorkIndex({locale='en'}:{locale?:Locale}){const g=growth(locale);return <><Header locale={locale} currentPath="/work"/><main id="main" tabIndex={-1}><section className="section wrap" id="work"><p className="eyebrow">{g.work}</p><h1>{g.allWork}</h1><p className="section-intro">{g.workDescription}</p><WorkGrid locale={locale}/></section><Contact locale={locale}/></main><Footer locale={locale}/></>;}
