import {getCase,caseOrder,filterIds,type Case,type CaseSlug} from '../content/cases';
import {growth} from '../content/growth';
import {localizePath,type Locale,Text} from '../lib/i18n';
import {WorkImage} from './work-image';
import {WorkFilters} from './growth-controls';
import {Header,Footer,Contact} from './portfolio-shell';
export function CaseCover({project,locale}:{project:Case;locale:Locale}){return <div className={'case-cover '+(project.images.length?'has-image':'generated-cover')}>{project.images.length?<WorkImage name={project.images[0].src} alt={project.client+' · '+project.images[0].caption}/>:<><span className="mono cover-sector"><Text locale={locale}>{project.sector}</Text></span><strong><bdi>{project.client}</bdi></strong><div className="chips">{project.channels.map(c=><bdi key={c}>{c}</bdi>)}</div></>}</div>;}
export function WorkGrid({locale,slugs=caseOrder}:{locale:Locale;slugs?:readonly CaseSlug[]}){const g=growth(locale);return <WorkFilters filters={filterIds.map((id,i)=>({id,label:g.filters[i]}))} cards={slugs.map(slug=>{const p=getCase(slug,locale);return {slug,filters:p.filters,node:<article className="work-card"><a href={localizePath('/work/'+slug,locale)}><CaseCover project={p} locale={locale}/><div className="work-caption"><div className="chips"><span>{p.sector}</span><span>{g[p.ownership]}</span></div><h3>{p.title}</h3>{p.metrics.length>0&&<p className="case-card-metric"><bdi>{p.metrics[0].value}</bdi> {p.metrics[0].label}</p>}<div className="chips muted-chips">{p.channels.map(c=><bdi key={c}>{c}</bdi>)}</div><span className="read-case">{g.readCase} <span className="icon-directional" aria-hidden="true">↗</span></span></div></a></article>};})}/>;}
export function WorkIndex({locale='en'}:{locale?:Locale}){const g=growth(locale);return <><Header locale={locale} currentPath="/work"/><main id="main" tabIndex={-1}><section className="section wrap" id="work"><p className="eyebrow">{g.work}</p><h1>{g.allWork}</h1><p className="section-intro">{g.workDescription}</p><WorkGrid locale={locale}/></section><Contact locale={locale}/></main><Footer locale={locale}/></>;}
