import fs from 'node:fs';
import {projects, projectRoles} from '../app/work/projects.ts';
import {experience, capabilities} from '../app/profile.ts';
import {clients} from '../app/clients.ts';
const en = {
 nav: {about:'About',experience:'Experience',work:'Work',clients:'Clients',cta:'Let’s talk',downloadCv:'Download CV'},
 a11y: {skipToContent:'Skip to content',openInNewTab:'opens in a new tab',languageSwitcher:'Change language',mainNavigation:'Main navigation',home:'Home',tools:'Tools and focus',languages:'Languages'},
 hero: {eyebrow:'Digital Marketing Manager',headline:'Paid social. Connected CRM.',accent:'Marketing that follows through.',availability:'Safi, Morocco · Working worldwide',services:['Paid social advertising','CRM & marketing automation','SEO & AI-powered content'],intro:'I connect the campaign, the content and the follow-up. Since 2018, I’ve helped international teams bring their marketing together, from the first impression to the next customer.',explore:'Explore my experience',selected:'Selected work',stats:[{value:'8+',label:'years in digital marketing'},{value:'3',label:'languages: English, French & Arabic'},{value:'{{ TODO: real metric }}',label:'client projects delivered'}]},
 about: {eyebrow:'A LITTLE ABOUT ME',headline:'Hi, I’m Mahdi.',accent:'Strategy meets doing.',lead:'A Digital Marketing Manager connecting creative ideas with the systems that make them work.',copy:'I work with international teams across paid social, SEO, content and CRM automation. From shaping a campaign to building its follow-up workflow, I enjoy being hands-on with the whole customer journey.',location:'Safi, Morocco',credentials:'Education & certifications',education:'Mathematics and Computer Science coursework at Université Cadi Ayyad (2015–2018). Social Media Marketing Professional Certification from the Institute of Management, Technology and Finance. Generative AI Certification from LinkedIn.',experience:'My experience'},
 sections: {experience:'PROFESSIONAL EXPERIENCE',experienceTitle:'A career built',experienceAccent:'by doing the work.',experienceIntro:'From community management to connected digital strategy.',exploreWork:'Explore the work',work:'SELECTED WORK',workTitle:'The strategy.',workAccent:'And the execution.',workIntro:'My role, the approach and what I delivered.',projects:'PROJECTS & SYSTEMS',projectsTitle:'Things I’ve',projectsAccent:'built and managed.',projectsIntro:'Publishing, automation and e-commerce in practice.',expertise:'EXPERTISE',expertiseTitle:'One perspective.',expertiseAccent:'The whole journey.',clients:'CLIENTS & COLLABORATIONS',clientsTitle:'Different industries.',clientsAccent:'A wider perspective.',clientsIntro:'From real estate and fitness to education, retail and hospitality. Explore the businesses and people I’ve worked with, including freelance and agency engagements.',directory:'Explore the client directory'},
 footer: {eyebrow:'HAVE A ROLE OR A PROJECT IN MIND?',headline:'Good work starts',accent:'with a conversation.',intro:'Open to digital marketing roles and freelance collaborations, remotely and worldwide.',location:'El Mahdi Bouizmoune · Safi, Morocco',backToTop:'Back to top',email:'Email Mahdi',book:'Book a call'},
 form: {name:'Name',email:'Email',company:'Company (optional)',message:'Message',submit:'Send message',pending:'Sending…',success:'Thank you. Your message has been sent.',failure:'Your message could not be sent. Please try again or use the email link below.',required:'Please complete this field.',invalidEmail:'Enter a valid email address, such as name@example.com.',tooShort:'Please write at least 10 characters.',tooLong:'Please shorten this entry.',slowDown:'Please wait a few seconds and try again.',privacy:'Your details are used to reply to your enquiry. Your message is processed by our email delivery provider, Resend. It is not sent to analytics.',website:'Leave this field empty',noJs:'Enable JavaScript to use this form, or use the email link below.'},
 directory: {back:'Back to selected work',headline:'Many businesses.',accent:'Individual stories.',intro:'Organizations, businesses and people I’ve supported through freelance work and agency engagements. Detailed case studies show my responsibilities and deliverables.',industries:'Client industries',caseStudy:'Case study',website:'Website',crmTitle:'Real estate CRM implementation',crm:'For a US real estate team, I configured kvCORE lead capture and routing, smart nurture campaigns, the IDX property-search site and pipeline stages. This was implementation work using Inside Real Estate’s platform for a client team.',employmentTitle:'Employment experience',employment:'My roles at Bunchful Enterprise, Generation Atomic and Strongman Corporation are covered in my professional experience and selected work.',logoTitle:'Selected collaborations',logoPending:'{{ TODO: approved client logo }}',testimonials:'Client feedback',testimonialPending:'{{ TODO: approved testimonial }}',personPending:'{{ TODO: name }}',rolePending:'{{ TODO: role }}',companyPending:'{{ TODO: company }}'},
 caseStudy: {allWork:'All work',role:'My role',problem:'Problem',actions:'What I did',result:'Result',proof:'Proof',next:'Next project',metric:'{{ TODO: metric }}',metricLabel:'{{ TODO: metric label }}',timeframe:'{{ TODO: timeframe }}',proofPending:'{{ TODO: approved screenshot or live proof link }}',caption:'Selected creative from my portfolio.',read:'Read the case study',thumbnail:'Campaign creative',proofAlt:'Selected campaign creative'},
 meta: {homeTitle:'El Mahdi Bouizmoune | Paid Social & CRM Manager',homeDescription:'Paid social, SEO, CRM automation and AI content. Explore El Mahdi Bouizmoune’s experience at Bunchful, Generation Atomic, AKAM and Strongman Corporation.',clientsTitle:'Clients & Collaborations',clientsDescription:'Explore El Mahdi Bouizmoune’s client experience across real estate, fitness, e-commerce, agencies, hospitality, education and media.',personDescription:'Digital marketing professional specializing in paid social advertising, CRM automation, SEO and AI content.',notFound:'Page not found',notFoundCopy:'This page is not available. Explore my experience or selected work from the homepage.',returnHome:'Return home'},
 experience, capabilities, clients,
 work: Object.fromEntries(projects.map(p=>[p.slug,{...p, ...projectRoles[p.slug],metrics:Array.from({length:3},()=>({value:'{{ TODO: metric }}',label:'{{ TODO: metric label }}',timeframe:'{{ TODO: timeframe }}'})),proof:{src:p.image||'',caption:p.image?'Selected creative from my portfolio.':'{{ TODO: approved screenshot or live proof link }}',href:''}}])),
 testimonials: Array.from({length:3},()=>({quote:'{{ TODO: approved testimonial }}',name:'{{ TODO: name }}',role:'{{ TODO: role }}',company:'{{ TODO: company }}',href:''})),
 logos: ['AKAM','Fresh Body','PRIMOVA','RetroChic','Raffaella','Skyrocket Your Biz','Gourmet Gather','Excilify'].map(name=>({name,src:''}))
};
// Existing evidence is retained verbatim. Metrics and endorsements remain explicit editorial slots.
for(const p of Object.values(en.work))delete p.source;
fs.mkdirSync('locales',{recursive:true});
fs.writeFileSync('locales/en.json',JSON.stringify(en,null,2)+'\n');
console.log('English content migrated.');
