import fs from 'node:fs';
const en=JSON.parse(fs.readFileSync('locales/en.json','utf8'));
const fr=structuredClone(en), ar=structuredClone(en);
fr.nav={about:'À propos',experience:'Expérience',work:'Réalisations',clients:'Clients',cta:'Échangeons',downloadCv:'Télécharger le CV'};
ar.nav={about:'نبذة عني',experience:'الخبرة',work:'الأعمال',clients:'العملاء',cta:'لنتواصل',downloadCv:'تحميل السيرة الذاتية'};
fr.a11y={skipToContent:'Aller au contenu',openInNewTab:'s’ouvre dans un nouvel onglet',languageSwitcher:'Changer de langue',mainNavigation:'Navigation principale',home:'Accueil',tools:'Outils et domaines',languages:'Langues'};
ar.a11y={skipToContent:'الانتقال إلى المحتوى',openInNewTab:'يفتح في علامة تبويب جديدة',languageSwitcher:'تغيير اللغة',mainNavigation:'التنقل الرئيسي',home:'الرئيسية',tools:'الأدوات والمجالات',languages:'اللغات'};
fr.hero={eyebrow:'Responsable marketing digital',headline:'Publicité sociale. CRM connecté.',accent:'Un marketing qui assure le suivi.',availability:'Safi, Maroc · Missions dans le monde entier',services:['Publicité sur les réseaux sociaux','CRM et automatisation marketing','SEO et contenu assisté par l’IA'],intro:'Je relie les campagnes, le contenu et le suivi client. Depuis 2018, j’aide des équipes internationales à coordonner leur marketing, du premier contact au prochain client.',explore:'Découvrir mon expérience',selected:'Réalisations sélectionnées',stats:[{value:'8+',label:'années en marketing digital'},{value:'3',label:'langues : anglais, français et arabe'},{value:'{{ TODO: real metric }}',label:'projets clients livrés'}]};
ar.hero={eyebrow:'مدير التسويق الرقمي',headline:'إعلانات اجتماعية. CRM متكامل.',accent:'تسويق يتابع كل خطوة.',availability:'آسفي، المغرب · أعمل مع فرق حول العالم',services:['الإعلانات على منصات التواصل الاجتماعي','CRM وأتمتة التسويق','SEO والمحتوى المدعوم بالذكاء الاصطناعي'],intro:'أربط الحملات بالمحتوى ومتابعة العملاء. منذ 2018، أساعد فرقاً دولية على تنسيق تسويقها، من الانطباع الأول إلى اكتساب العميل التالي.',explore:'اطّلع على خبرتي',selected:'أعمال مختارة',stats:[{value:'8+',label:'سنوات في التسويق الرقمي'},{value:'3',label:'لغات: الإنجليزية والفرنسية والعربية'},{value:'{{ TODO: real metric }}',label:'مشاريع عملاء تم تسليمها'}]};
fr.about={eyebrow:'QUELQUES MOTS SUR MOI',headline:'Bonjour, je suis Mahdi.',accent:'De la stratégie à la pratique.',lead:'Responsable marketing digital, je relie les idées créatives aux systèmes qui les concrétisent.',copy:'Je travaille avec des équipes internationales sur la publicité sociale, le SEO, le contenu et l’automatisation CRM. De la conception d’une campagne à ses scénarios de suivi, j’aime intervenir sur l’ensemble du parcours client.',location:'Safi, Maroc',credentials:'Formation et certifications',education:'Cours de mathématiques et d’informatique à l’Université Cadi Ayyad (2015–2018). Certification professionnelle en marketing des réseaux sociaux de l’Institute of Management, Technology and Finance. Certification en IA générative de LinkedIn.',experience:'Mon expérience'};
ar.about={eyebrow:'نبذة عني',headline:'مرحباً، أنا Mahdi.',accent:'أحوّل الاستراتيجية إلى عمل.',lead:'مدير تسويق رقمي يربط الأفكار الإبداعية بالأنظمة التي تساعد على تنفيذها.',copy:'أعمل مع فرق دولية في الإعلانات الاجتماعية وSEO والمحتوى وأتمتة CRM. من صياغة الحملة إلى بناء مسار المتابعة، أفضّل العمل مباشرة على رحلة العميل بأكملها.',location:'آسفي، المغرب',credentials:'التعليم والشهادات',education:'دراسة مقررات الرياضيات وعلوم الحاسوب في Université Cadi Ayyad خلال 2015–2018. شهادة مهنية في التسويق عبر وسائل التواصل الاجتماعي من Institute of Management, Technology and Finance. شهادة في الذكاء الاصطناعي التوليدي من LinkedIn.',experience:'خبرتي المهنية'};
fr.sections={experience:'EXPÉRIENCE PROFESSIONNELLE',experienceTitle:'Un parcours construit',experienceAccent:'sur le terrain.',experienceIntro:'De la gestion de communauté à une stratégie digitale coordonnée.',exploreWork:'Découvrir les réalisations',work:'RÉALISATIONS SÉLECTIONNÉES',workTitle:'La stratégie.',workAccent:'Et sa mise en œuvre.',workIntro:'Mon rôle, ma démarche et mes livrables.',projects:'PROJETS ET SYSTÈMES',projectsTitle:'Ce que j’ai',projectsAccent:'construit et géré.',projectsIntro:'Publication, automatisation et e-commerce en pratique.',expertise:'EXPERTISE',expertiseTitle:'Une même vision.',expertiseAccent:'Tout le parcours.',clients:'CLIENTS ET COLLABORATIONS',clientsTitle:'Des secteurs variés.',clientsAccent:'Une perspective élargie.',clientsIntro:'De l’immobilier au sport, en passant par la formation, le commerce et l’hôtellerie. Découvrez les entreprises et les personnes que j’ai accompagnées, en freelance et en agence.',directory:'Consulter le répertoire clients'};
ar.sections={experience:'الخبرة المهنية',experienceTitle:'مسار مهني بنيته',experienceAccent:'بالممارسة.',experienceIntro:'من إدارة المجتمعات إلى استراتيجية رقمية مترابطة.',exploreWork:'استكشف العمل',work:'أعمال مختارة',workTitle:'الاستراتيجية.',workAccent:'والتنفيذ.',workIntro:'دوري ومنهجي وما سلّمته.',projects:'المشاريع والأنظمة',projectsTitle:'ما قمت',projectsAccent:'ببنائه وإدارته.',projectsIntro:'النشر والأتمتة والتجارة الإلكترونية في التطبيق.',expertise:'مجالات الخبرة',expertiseTitle:'رؤية واحدة.',expertiseAccent:'لرحلة العميل كاملة.',clients:'العملاء والتعاونات',clientsTitle:'قطاعات متنوعة.',clientsAccent:'منظور أوسع.',clientsIntro:'من العقارات واللياقة إلى التعليم والتجارة والضيافة. تعرّف على الشركات والأشخاص الذين عملت معهم، ضمن مشاريع مستقلة وتعاونات مع وكالات.',directory:'استعرض دليل العملاء'};
fr.footer={eyebrow:'UN POSTE OU UN PROJET EN TÊTE ?',headline:'Une collaboration commence',accent:'par une conversation.',intro:'Disponible pour des postes en marketing digital et des missions freelance, à distance et dans le monde entier.',location:'El Mahdi Bouizmoune · Safi, Maroc',backToTop:'Retour en haut',email:'Envoyer un e-mail à Mahdi',book:'Réserver un appel'};
ar.footer={eyebrow:'هل لديكم فرصة عمل أو مشروع؟',headline:'يبدأ العمل الجيد',accent:'بمحادثة.',intro:'متاح لفرص العمل في التسويق الرقمي والتعاون المستقل، عن بُعد ومع فرق حول العالم.',location:'El Mahdi Bouizmoune · آسفي، المغرب',backToTop:'العودة إلى الأعلى',email:'راسل Mahdi بالبريد',book:'احجز مكالمة'};
fr.form={name:'Nom',email:'E-mail',company:'Entreprise (facultatif)',message:'Message',submit:'Envoyer le message',pending:'Envoi en cours…',success:'Merci. Votre message a été envoyé.',failure:'Votre message n’a pas pu être envoyé. Réessayez ou utilisez le lien e-mail ci-dessous.',required:'Veuillez remplir ce champ.',invalidEmail:'Saisissez une adresse e-mail valide, par exemple nom@exemple.com.',tooShort:'Veuillez écrire au moins 10 caractères.',tooLong:'Veuillez raccourcir ce texte.',slowDown:'Patientez quelques secondes avant de réessayer.',privacy:'Vos coordonnées servent à répondre à votre demande. Votre message est traité par notre prestataire d’envoi d’e-mails, Resend. Il n’est pas transmis aux outils statistiques.',website:'Laissez ce champ vide',noJs:'Activez JavaScript pour utiliser ce formulaire, ou utilisez le lien e-mail ci-dessous.'};
ar.form={name:'الاسم',email:'البريد الإلكتروني',company:'الشركة (اختياري)',message:'الرسالة',submit:'إرسال الرسالة',pending:'جارٍ الإرسال…',success:'شكراً لكم. تم إرسال رسالتكم.',failure:'تعذّر إرسال الرسالة. يرجى المحاولة مجدداً أو استخدام رابط البريد أدناه.',required:'يرجى تعبئة هذا الحقل.',invalidEmail:'أدخلوا عنوان بريد صحيحاً، مثل name@example.com.',tooShort:'يرجى كتابة 10 أحرف على الأقل.',tooLong:'يرجى اختصار النص.',slowDown:'يرجى الانتظار بضع ثوانٍ ثم المحاولة مجدداً.',privacy:'تُستخدم بياناتكم للرد على استفساركم. تعالج خدمة Resend رسالتكم لإيصال البريد. لا نرسل محتوى الرسالة إلى أدوات التحليلات.',website:'اتركوا هذا الحقل فارغاً',noJs:'فعّلوا JavaScript لاستخدام النموذج، أو استخدموا رابط البريد أدناه.'};
fr.directory={...en.directory,back:'Retour aux réalisations',headline:'De nombreuses entreprises.',accent:'Des histoires singulières.',intro:'Organisations, entreprises et personnes accompagnées en freelance ou en agence. Les études de cas détaillent mes responsabilités et mes livrables.',industries:'Secteurs des clients',caseStudy:'Étude de cas',website:'Site web',crmTitle:'Mise en place de CRM immobilier',crm:'Pour une équipe immobilière américaine, j’ai configuré la collecte et l’attribution des prospects dans kvCORE, les campagnes de suivi, la recherche de biens IDX et les étapes du pipeline. Il s’agissait de déployer la plateforme Inside Real Estate pour une équipe cliente.',employmentTitle:'Expérience salariée',employment:'Mes postes chez Bunchful Enterprise, Generation Atomic et Strongman Corporation figurent dans mon expérience professionnelle et mes réalisations.',logoTitle:'Quelques collaborations',testimonials:'Retours clients'};
ar.directory={...en.directory,back:'العودة إلى الأعمال المختارة',headline:'شركات عديدة.',accent:'وقصص مختلفة.',intro:'مؤسسات وشركات وأفراد دعمتهم من خلال العمل المستقل والتعاون مع الوكالات. توضّح دراسات الحالة مسؤولياتي وما سلّمته.',industries:'قطاعات العملاء',caseStudy:'دراسة الحالة',website:'الموقع الإلكتروني',crmTitle:'تنفيذ أنظمة CRM للعقارات',crm:'لفريق عقاري أمريكي، أعددت جمع العملاء المحتملين وتوزيعهم في kvCORE، وحملات المتابعة، وموقع البحث العقاري IDX، ومراحل مسار المبيعات. كان العمل تنفيذاً لمنصة Inside Real Estate لصالح فريق عميل.',employmentTitle:'الخبرة الوظيفية',employment:'تجدون أدواري لدى Bunchful Enterprise وGeneration Atomic وStrongman Corporation ضمن الخبرة المهنية والأعمال المختارة.',logoTitle:'تعاونات مختارة',testimonials:'آراء العملاء'};
fr.caseStudy={...en.caseStudy,allWork:'Toutes les réalisations',role:'Mon rôle',problem:'Problème',actions:'Mes actions',result:'Résultat',proof:'Éléments de preuve',next:'Projet suivant',caption:'Création sélectionnée dans mon portfolio.',read:'Lire l’étude de cas',thumbnail:'Création de campagne',proofAlt:'Création de campagne sélectionnée'};
ar.caseStudy={...en.caseStudy,allWork:'جميع الأعمال',role:'دوري',problem:'المشكلة',actions:'ما قمت به',result:'النتيجة',proof:'الأدلة',next:'المشروع التالي',caption:'نموذج إبداعي مختار من ملف أعمالي.',read:'اقرأ دراسة الحالة',thumbnail:'تصميم للحملة',proofAlt:'تصميم مختار من الحملة'};
fr.meta={homeTitle:'El Mahdi Bouizmoune | Publicité sociale et CRM',homeDescription:'Publicité sociale, SEO, automatisation CRM et contenu IA. Découvrez l’expérience d’El Mahdi Bouizmoune chez Bunchful, Generation Atomic, AKAM et Strongman Corporation.',clientsTitle:'Clients et collaborations',clientsDescription:'Découvrez les missions d’El Mahdi Bouizmoune dans l’immobilier, le sport, l’e-commerce, les agences, l’hôtellerie, la formation et les médias.',personDescription:'Professionnel du marketing digital spécialisé en publicité sociale, automatisation CRM, SEO et contenu IA.',notFound:'Page introuvable',notFoundCopy:'Cette page n’est pas disponible. Découvrez mon expérience et mes réalisations depuis l’accueil.',returnHome:'Retour à l’accueil'};
ar.meta={homeTitle:'El Mahdi Bouizmoune | الإعلانات الاجتماعية وCRM',homeDescription:'إعلانات اجتماعية وSEO وأتمتة CRM ومحتوى بالذكاء الاصطناعي. استكشفوا خبرة El Mahdi Bouizmoune لدى Bunchful وGeneration Atomic وAKAM وStrongman Corporation.',clientsTitle:'العملاء والتعاونات',clientsDescription:'استكشفوا خبرة El Mahdi Bouizmoune مع عملاء في العقارات واللياقة والتجارة الإلكترونية والوكالات والضيافة والتعليم والإعلام.',personDescription:'متخصص في التسويق الرقمي والإعلانات الاجتماعية وأتمتة CRM وSEO والمحتوى المدعوم بالذكاء الاصطناعي.',notFound:'الصفحة غير موجودة',notFoundCopy:'هذه الصفحة غير متاحة. استكشفوا خبرتي وأعمالي المختارة من الصفحة الرئيسية.',returnHome:'العودة إلى الرئيسية'};
const expFR=[
 ['Bunchful Enterprise','Responsable marketing digital','Mai 2023 – Aujourd’hui','New York · À distance','Stratégie digitale couvrant le SEO, les réseaux sociaux, le contenu et l’automatisation e-mail. Optimisation WordPress, rapports GA4 et gestion des ressources numériques dans Adobe Experience.'],
 ['Conseil indépendant · Fiverr','Consultant freelance en marketing digital','Janv. 2018 – Aujourd’hui','Monde entier · À distance','Acquisition payante, contenu social et marketing relationnel pour des startups et des marques établies. Gestion de campagnes sur Meta, TikTok, LinkedIn et Pinterest.'],
 ['AKAM Real Estate','Responsable réseaux sociaux · Freelance','Févr. 2024 – Mars 2025','New York · À distance','Stratégie sociale pour un projet résidentiel new-yorkais : calendriers éditoriaux, animation de communauté et guide de contenu réutilisable.'],
 ['Generation Atomic','Spécialiste marketing digital','Janv. 2022 – Mai 2023','Minnesota · À distance','Réseaux sociaux, calendriers éditoriaux, recherche de mots-clés, SEO sur page, analyses, opérations e-commerce et campagnes événementielles.'],
 ['Strongman Corporation','Responsable de communauté','Févr. 2018 – Janv. 2022','Columbus, Ohio · À distance','Calendriers éditoriaux, gestion de communauté et promotion payante d’événements nationaux, avec production créative et mises à jour WordPress.']
];
const expAR=[
 ['Bunchful Enterprise','مدير التسويق الرقمي','مايو 2023 – حتى الآن','New York · عن بُعد','استراتيجية رقمية تشمل SEO والتواصل الاجتماعي والمحتوى وأتمتة البريد. تحسين WordPress وتقارير GA4 وإدارة الأصول الرقمية في Adobe Experience.'],
 ['استشارات مستقلة · Fiverr','مستشار مستقل في التسويق الرقمي','يناير 2018 – حتى الآن','حول العالم · عن بُعد','اكتساب العملاء بالإعلانات والمحتوى الاجتماعي وتسويق دورة حياة العميل للشركات الناشئة والعلامات القائمة. إدارة الحملات على Meta وTikTok وLinkedIn وPinterest.'],
 ['AKAM Real Estate','مدير وسائل التواصل الاجتماعي · مستقل','فبراير 2024 – مارس 2025','New York · عن بُعد','استراتيجية اجتماعية لمشروع سكني في نيويورك، تشمل تقاويم المحتوى والتفاعل مع المجتمع ودليل محتوى قابل لإعادة الاستخدام.'],
 ['Generation Atomic','متخصص التسويق الرقمي','يناير 2022 – مايو 2023','Minnesota · عن بُعد','إدارة التواصل الاجتماعي والتقاويم التحريرية وبحث الكلمات المفتاحية وSEO والتحليلات وعمليات التجارة الإلكترونية والحملات الخاصة بالفعاليات.'],
 ['Strongman Corporation','مدير المجتمع','فبراير 2018 – يناير 2022','Columbus, Ohio · عن بُعد','تقاويم تحريرية وإدارة المجتمع وترويج مدفوع للفعاليات الوطنية، مع إنتاج التصاميم وتحديث موقع WordPress.']
];
for(const [d,rows] of [[fr,expFR],[ar,expAR]])d.experience.forEach((e,i)=>['company','role','period','location','copy'].forEach((k,j)=>e[k]=rows[i][j]));
const capsFR=[['Publicité sociale et acquisition','Stratégie de campagne, tests créatifs et suivi des conversions reliant les dépenses publicitaires au parcours client.'],['Automatisation marketing et CRM','Collecte de prospects, pipelines structurés et suivi e-mail/SMS, de la première demande au rendez-vous.'],['SEO, contenu et analyse','Contenu utile fondé sur l’intention de recherche, améliorations techniques et rapports pour guider les décisions.'],['Contenu IA et e-commerce','Systèmes de publication et gestion de boutiques associant direction humaine et production assistée par l’IA.']];
const capsAR=[['الإعلانات الاجتماعية واكتساب العملاء','استراتيجية الحملات واختبار التصاميم وتتبع التحويلات لربط الإنفاق الإعلاني برحلة العميل.'],['أتمتة التسويق وCRM','جمع العملاء المحتملين وتنظيم مسارات المبيعات والمتابعة بالبريد والرسائل، من أول استفسار إلى حجز موعد.'],['SEO والمحتوى والتحليلات','محتوى مفيد يستند إلى نية البحث، مع تحسينات تقنية وتقارير تساعد على اتخاذ القرار التالي.'],['محتوى الذكاء الاصطناعي والتجارة الإلكترونية','أنظمة نشر وعمليات متاجر تجمع التوجيه البشري والإنتاج بمساعدة الذكاء الاصطناعي.']];
for(const [d,rows]of [[fr,capsFR],[ar,capsAR]])d.capabilities.forEach((c,i)=>{c.title=rows[i][0];c.copy=rows[i][1]});
// Work and directory translations are completed in the following authoring module.
fs.writeFileSync('locales/fr.json',JSON.stringify(fr,null,2)+'\n');fs.writeFileSync('locales/ar.json',JSON.stringify(ar,null,2)+'\n');
